apiVersion: apps/v1
kind: Deployment
metadata:
  name: lpp-stations
spec:
  selector:
    matchLabels:
      app: lpp-stations
  replicas: 1
  template:
    metadata:
      labels:
        app: lpp-stations
    spec:
      containers:
        - image: bezpov/lpp-stations:1.0.2
          name: lpp-stations-container
          env:
            - name: ETCD_SERVER
              value: "http://etcd-client:2379"
          ports:
            - containerPort: 8092
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8092
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8092
            initialDelaySeconds: 20
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: lpp-stations-service
  namespace: default
  labels:
    app: lpp-stations
spec:
  ports:
    - protocol: TCP
      port: 93
      targetPort: 8092
  selector:
    app: lpp-stations
  type: NodePort